#! /usr/bin/env node
require('dotenv').config();

const _ = require('lodash');
const { promisify } = require('util');
const { exists: e, mkdir: m, writeFile: w } = require('fs');
const { join } = require('path');

const { getStaticSlugsForContentType, getGlobalSettings } = require('./src/integrations/contentful');

const exists = promisify(e);
const mkdir = promisify(m);
const writeFile = promisify(w);

const CONTENT_DIR = './content-cache';
const PATHS_JSON_FILE = join(CONTENT_DIR, 'paths.json');
const SETTINGS_JSON_FILE = join(CONTENT_DIR, 'settings.json');
const PAGE_GENERAL = 'pageGeneral';

const mkdirIfNotExists = async () => {
  if (!(await exists(CONTENT_DIR))) {
    mkdir(CONTENT_DIR);
  }
};

const writePathsJson = async ({ pageGeneralSlugs }) => {
  const firstLevelPaths = _.map(pageGeneralSlugs, (slug) => ({ params: { slug } }));
  const out = JSON.stringify({ '/': firstLevelPaths }, null, 2);
  writeFile(PATHS_JSON_FILE, out);
};

const writeSettingsJson = async (globalSettings) => {
  const out = JSON.stringify(globalSettings, null, 2);
  writeFile(SETTINGS_JSON_FILE, out);
};

const build = async () => {
  await mkdirIfNotExists();

  const [pageGeneralSlugs, globalSettings] = await Promise.all([
    getStaticSlugsForContentType(PAGE_GENERAL),
    getGlobalSettings()
  ]);

  await Promise.all([writePathsJson({ pageGeneralSlugs }), writeSettingsJson(globalSettings)]);
};

build()
  .then('Successfully wrote content files')
  .catch((err) => {
    process.stderr.write(`Unable to write content files:\n${err.message}`);
  });
