[build]
  functions = "serverless"

[dev]
  command = "npm run start:dev"
  functions = "serverless"
  publish = "public"

# Netlify offers the ability to configure the Redirects, Rewrites, Proxying and Headers directly in this *.toml configuration file. Please see the README for links to Netlify documentation.

[[redirects]]
  from = "/toml"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/hello-world"
  to = "/.netlify/functions/hello-world"
  status = 200
  force = true # COMMENT: ensure that we always redirect even if file present

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Header-Source = "netlify.toml"

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Header-Source = "netlify.toml"